package castlevaniabot.strategy;

import castlevaniabot.BotState;
import castlevaniabot.CastlevaniaBot;
import lombok.Value;

@Value
public class AllStrategies {
    private final AxeStrategy AXE;
    private final AxeKnightStrategy AXE_KNIGHT;
    private final BatMovingPlatformStrategy BAT_MOVING_PLATFORM;
    private final BatDualPlatformsStrategy BAT_DUAL_PLATFORMS;
    private final BoneDragonStrategy BONE_DRAGON;
    private final BlackBatStrategy BLACK_BAT;
    private final BlockStrategy BLOCK;
    private final BoomerangDeathStrategy BOOMERANG_DEATH;
    private final BoneStrategy BONE;
    private final BoneTowerStrategy BONE_TOWER;
    private final CandlesStrategy CANDLES;
    private final CookieMonsterStrategy COOKIE_MONSTER;
    private final CrusherStrategy CRUSHER;
    private final DeathHallHolyWaterStrategy DEATH_HALL_HOLY_WATER;
    private final DraculaStrategy DRACULA;
    private final EagleStrategy EAGLE;
    private final FireballStrategy FIREBALL;
    private final FireColumnStrategy FIRE_COLUMN;
    private final FishmanStrategy FISHMAN;
    private final FleamanStrategy FLEAMAN;
    private final FrankensteinStrategy FRANKENSTEIN;
    private final GetCrystalBallStrategy GET_CRYSTAL_BALL;
    private final GetItemStrategy GET_ITEM;
    private final GhostStrategy GHOST;
    private final GhoulStrategy GHOUL;
    private final GiantBatStrategy GIANT_BAT;
    private final GotCrystalBallStrategy GOT_CRYSTAL_BALL;
    private final HolyWaterDeathStrategy HOLY_WATER_DEATH;
    private final JumpMovingPlatformStrategy JUMP_MOVING_PLATFORM;
    private final MedusaStrategy MEDUSA;
    private final MedusaHeadStrategy MEDUSA_HEAD;
    private final MedusaHeadsPitsStrategy MEDUSA_HEADS_PITS;
    private final MedusaHeadsWalkStrategy MEDUSA_HEADS_WALK;
    private final MummiesStrategy MUMMIES;
    private final NoJumpMovingPlatformStrategy NO_JUMP_MOVING_PLATFORM;
    private final PantherStrategy PANTHER;
    private final PhantomBatStrategy PHANTOM_BAT;
    private final RavenStrategy RAVEN;
    private final RedBatDamageBoostStrategy RED_BAT_DAMAGE_BOOST;
    private final RedBatStrategy RED_BAT;
    private final RedBonesStrategy RED_BONES;
    private final RedSkeletonStrategy RED_SKELETON;
    private final SickleStrategy SICKLE;
    private final SkeletonWallStrategy SKELETON_WALL;
    private final SnakeStrategy SNAKE;
    private final SpearKnightStrategy SPEAR_KNIGHT;
    private final UseWeaponStrategy USE_WEAPON;
    private final WaitStrategy WAIT;
    private final WhiteSkeletonStrategy WHITE_SKELETON;
    private final WhipStrategy WHIP;

    public AllStrategies(CastlevaniaBot castlevaniaBot, BotState botState) {
        AXE = new AxeStrategy(castlevaniaBot, botState);
        AXE_KNIGHT = new AxeKnightStrategy(castlevaniaBot, botState);
        BAT_MOVING_PLATFORM = new BatMovingPlatformStrategy(castlevaniaBot, botState);
        BAT_DUAL_PLATFORMS = new BatDualPlatformsStrategy(castlevaniaBot, botState);
        BONE_DRAGON = new BoneDragonStrategy(castlevaniaBot, botState);
        BLACK_BAT = new BlackBatStrategy(castlevaniaBot, botState);
        BLOCK = new BlockStrategy(castlevaniaBot, botState);
        BOOMERANG_DEATH = new BoomerangDeathStrategy(castlevaniaBot, botState);
        BONE = new BoneStrategy(castlevaniaBot, botState);
        BONE_TOWER = new BoneTowerStrategy(castlevaniaBot, botState);
        CANDLES = new CandlesStrategy(castlevaniaBot, botState);
        COOKIE_MONSTER = new CookieMonsterStrategy(castlevaniaBot, botState);
        CRUSHER = new CrusherStrategy(castlevaniaBot, botState);
        DEATH_HALL_HOLY_WATER = new DeathHallHolyWaterStrategy(castlevaniaBot, botState);
        DRACULA = new DraculaStrategy(castlevaniaBot, botState);
        EAGLE = new EagleStrategy(castlevaniaBot, botState);
        FIREBALL = new FireballStrategy(castlevaniaBot, botState);
        FIRE_COLUMN = new FireColumnStrategy(castlevaniaBot, botState);
        FISHMAN = new FishmanStrategy(castlevaniaBot, botState);
        FLEAMAN = new FleamanStrategy(castlevaniaBot, botState);
        FRANKENSTEIN = new FrankensteinStrategy(castlevaniaBot, botState);
        GET_CRYSTAL_BALL = new GetCrystalBallStrategy(castlevaniaBot, botState);
        GET_ITEM = new GetItemStrategy(castlevaniaBot, botState);
        GHOST = new GhostStrategy(castlevaniaBot, botState);
        GHOUL = new GhoulStrategy(castlevaniaBot, botState);
        GIANT_BAT = new GiantBatStrategy(castlevaniaBot, botState);
        GOT_CRYSTAL_BALL = new GotCrystalBallStrategy(castlevaniaBot, botState);
        HOLY_WATER_DEATH = new HolyWaterDeathStrategy(castlevaniaBot, botState);
        JUMP_MOVING_PLATFORM = new JumpMovingPlatformStrategy(castlevaniaBot, botState);
        MEDUSA = new MedusaStrategy(castlevaniaBot, botState);
        MEDUSA_HEAD = new MedusaHeadStrategy(castlevaniaBot, botState);
        MEDUSA_HEADS_PITS = new MedusaHeadsPitsStrategy(castlevaniaBot, botState);
        MEDUSA_HEADS_WALK = new MedusaHeadsWalkStrategy(castlevaniaBot, botState);
        MUMMIES = new MummiesStrategy(castlevaniaBot, botState);
        NO_JUMP_MOVING_PLATFORM = new NoJumpMovingPlatformStrategy(castlevaniaBot, botState);
        PANTHER = new PantherStrategy(castlevaniaBot, botState);
        PHANTOM_BAT = new PhantomBatStrategy(castlevaniaBot, botState);
        RAVEN = new RavenStrategy(castlevaniaBot, botState);
        RED_BAT_DAMAGE_BOOST = new RedBatDamageBoostStrategy(castlevaniaBot, botState);
        RED_BAT = new RedBatStrategy(castlevaniaBot, botState);
        RED_BONES = new RedBonesStrategy(castlevaniaBot, botState);
        RED_SKELETON = new RedSkeletonStrategy(castlevaniaBot, botState);
        SICKLE = new SickleStrategy(castlevaniaBot, botState);
        SKELETON_WALL = new SkeletonWallStrategy(castlevaniaBot, botState);
        SNAKE = new SnakeStrategy(castlevaniaBot, botState);
        SPEAR_KNIGHT = new SpearKnightStrategy(castlevaniaBot, botState);
        USE_WEAPON = new UseWeaponStrategy(castlevaniaBot, botState);
        WAIT = new WaitStrategy(castlevaniaBot, botState);
        WHITE_SKELETON = new WhiteSkeletonStrategy(castlevaniaBot, botState);
        WHIP = new WhipStrategy(castlevaniaBot, botState);
    }
}
